package server;

public enum MessageType {
    USER_REQUEST_DB,
    USER,
    USER_ACCEPTED,
    USER_NOT_ACCEPTED,
    TEXT,
    USER_ADDED,
    USER_REMOVED,
    CLOSE_CONNECTION,
    USER_REGISTRATION,
    REGISTRATION_ALLOWED,
    REGISTRATION_ACCEPTED,
    REGISTRATION_NOT_ACCEPTED,
    REG_USER
}
